name: CI - Cache Tests

on:
  push:
    branches: [ feature/tests ]
  pull_request:
    branches: [ feature/tests ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Run cache tests
        working-directory: ./lab5
        run: go test -v -cover ./internal/pkg/cache/...
